Connezione al server SQL Server

In [7]:
import pyodbc as odbc
import pandas as pd

conn = odbc.connect(
    r"""
    Driver={ODBC Driver 17 for SQL Server};
    Server=(localdb)\P;
    Database=ScuolaDb;
    Trusted_Connection=yes;
    TrustServerCertificate=yes;
    """
)

print("✅ Connessione riuscita!")

✅ Connessione riuscita!

Visualizzazione della lista degli studenti

In [31]:

df = pd.read_sql("EXEC sp_GetAllStudenti", conn)
df

C:\Users\salis\AppData\Local\Temp\ipykernel_23720\3906164993.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("EXEC sp_GetAllStudenti", conn)

,StudenteId,Nome,Cognome,DataNascita,EMAIL,CodiceFiscale
0,1,Luca,Bianchi,1999-11-03,luca.bianchi@email.com,BNCLCU99S03F205X
1,2,Giulia,Verdi,2001-02-20,giulia.verdi@email.com,VRDGLI01B60H501Y
2,3,Anna,Ferrari,2002-07-15,anna.ferrari@email.com,FRRNNA02L55D612T
3,4,Marco,Romano,1998-09-28,marco.romano@email.com,RMNMRC98P28H501U
4,5,Mario,Rossi,2000-01-10,mario1@email.com,RSSMRA00A10H501A
5,6,Luca,Bianchi,1999-02-11,luca2@email.com,BNCLCU99B11H501B
6,7,Giulia,Verdi,2001-03-12,giulia3@email.com,VRDGLI01C12H501C
7,8,Anna,Ferrari,2002-04-13,anna4@email.com,FRRNNA02D13H501D
8,9,Marco,Romano,1998-05-14,marco5@email.com,RMNMRC98E14H501E
9,10,Paolo,Ricci,2000-06-15,paolo6@email.com,RCCPLA00F15H501F
10,11,Sara,Gallo,2001-07-16,sara7@email.com,GLLSRA01G16H501G
11,12,Davide,Costa,1999-08-17,davide8@email.com,CSTDVD99H17H501H
12,13,Elena,Fontana,2002-09-18,elena9@email.com,FNTLNE02I18H501I
13,14,Simone,Greco,2000-10-19,simone10@email.com,GRCSMN00L19H501L
14,15,Francesca,Conti,2001-11-20,francesca11@email.com,CNTFNC01M20H501M
15,16,Andrea,DeLuca,1999-12-21,andrea12@email.com,DLCNDR99N21H501N
16,17,Chiara,Marino,2002-01-22,chiara13@email.com,MRNCHR02A22H501O
17,18,Alessio,Riva,2000-02-23,alessio14@email.com,RVALSS00B23H501P
18,19,Valentina,Lombardi,2001-03-24,valentina15@email.com,LMBVLT01C24H501Q
19,20,Giorgio,Barbieri,1998-04-25,giorgio16@email.com,BRBGRG98D25H501R
20,21,Martina,Moretti,2002-05-26,martina17@email.com,MRTMTN02E26H501S
21,22,Stefano,Ferraro,2000-06-27,stefano18@email.com,FRRSTF00F27H501T
22,23,Roberta,Caruso,1999-07-28,roberta19@email.com,CRSRRT99G28H501U
23,24,Alberto,Giordano,2001-08-29,alberto20@email.com,GRDLRT01H29H501V
24,25,Federica,Colombo,2002-09-30,federica21@email.com,CLMFRC02I30H501W
25,26,Claudio,Silvestri,2000-10-01,claudio22@email.com,SLVCLD00L01H501X
26,27,Marta,Testa,2001-11-02,marta23@email.com,TSTMRT01M02H501Y
27,28,Daniele,Villa,1999-12-03,daniele24@email.com,VLLDNL99N03H501Z
28,29,Silvia,Serra,2002-01-04,silvia25@email.com,SRRSVL02A04H501A
29,30,Emanuele,Leone,2000-02-05,l.emanuele26@gmail.com,LNEEMN00B05H501B
30,31,Ilaria,Santoro,2001-03-06,ilaria27@email.com,SNTLRI01C06H501C
31,32,Matteo,Fiore,1998-04-07,matteo28@email.com,FRIMTT98D07H501D
32,33,Noemi,Ruggiero,2002-05-08,noemi29@email.com,RGGNMI02E08H501E
33,34,Fabio,Pellegrini,2000-06-09,fabio30@email.com,PLLFBI00F09H501F
34,35,Pippo,Bobbo,2000-11-20,b.pippo@gmail.com,PIBBWNA02L45D612

Salva in excel

In [33]:
df.to_excel("studenti.xlsx", index=False)
print("📂 File Excel creato con successo!")

📂 File Excel creato con successo!

Visualizza la lista degli studenti che hanno voti sopra la media

In [27]:
df = pd.read_sql("sp_VotoStudentiSopraMedia", conn)
df

C:\Users\salis\AppData\Local\Temp\ipykernel_23720\1596843185.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("sp_VotoStudentiSopraMedia", conn)

    StudenteId Nome completo dello Studente
0            1                 Luca Bianchi
1            2                 Giulia Verdi
2            4                 Marco Romano
3            5                  Mario Rossi
4            8                 Anna Ferrari
5           10                  Paolo Ricci
6           13                Elena Fontana
7           14                 Simone Greco
8           15              Francesca Conti
9           19           Valentina Lombardi
10          20             Giorgio Barbieri
11          22              Stefano Ferraro
12          23               Roberta Caruso
13          24             Alberto Giordano
14          28                Daniele Villa
15          29                 Silvia Serra
16          30               Emanuele Leone

SALVATAGGIO DEGLI STUDENTI NEL FILE DI EXCEL

In [28]:
df.to_excel("studente.xlsx", index=False)
print("📂 File Excel creato con successo!")

📂 File Excel creato con successo!

Restutuisce lo studete = 1

In [ ]:
df = pd.read_sql("EXEC sp_GetStudenteById", (30,) conn)
df

SyntaxError: invalid syntax. Perhaps you forgot a comma? (4243019816.py, line 1)

Restutuisce lo studente con nome = Marco

In [35]:
df = pd.read_sql("EXEC sp_GetStudenteByName 'Marco';", conn)
df

C:\Users\salis\AppData\Local\Temp\ipykernel_23720\336561695.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("EXEC sp_GetStudenteByName 'Marco';", conn)

,StudenteId,Nome,Cognome,DataNascita,EMAIL,CodiceFiscale
0,4,Marco,Romano,1998-09-28,marco.romano@email.com,RMNMRC98P28H501U
1,9,Marco,Romano,1998-05-14,marco5@email.com,RMNMRC98E14H501E

Inserimento di uno studente

EXEC sp_InsertStudente 'Pippo', 'Bobbo', '2000-11-20', 'b.pippo@gmail.com', 'PIBBWNA02L45D612P';
EXEC sp_UpdateEmailStudente 30, 'l.emanuele26@gmail.com'


EXEC sp_VotiSopraMedia;

In [15]:
import pyodbc as odbc
import pandas as pd

conn = odbc.connect(
    r"""
    Driver={ODBC Driver 17 for SQL Server};
    Server=(localdb)\P;
    Database=ScuolaDb;
    Trusted_Connection=yes;
    TrustServerCertificate=yes;
    """
)

cursor = conn.cursor()

cursor.execute("""
     EXEC sp_InsertStudente ?, ?, ?, ?, ?
 """, ("Pastore", "Cosimo", "1988-11-04", ".cosimo@gmail.com", "PSTRWNA02L45D07"))